if __name__ == "__main__":

    import ROOT
    import argparse

    lowX=0.18
    lowY=0.835
    lumi  = ROOT.TPaveText(lowX, lowY+0.06, lowX+0.30, lowY+0.16, "NDC")
    lumi.SetBorderSize(   0 )
    lumi.SetFillStyle(    0 )
    lumi.SetTextAlign(   12 )
    lumi.SetTextColor(    1 )
    lumi.SetTextSize(0.04)
    lumi.SetTextFont (   42 )
    lumi.AddText("2018, 59.5 fb^{-1} (13 TeV)")

    lowX=0.18
    lowY=0.70
    lumi2  = ROOT.TPaveText(lowX, lowY+0.06, lowX+0.15, lowY+0.16, "NDC")
    lumi2.SetTextFont(61)
    lumi2.SetTextSize(0.04)
    lumi2.SetBorderSize(   0 )
    lumi2.SetFillStyle(    0 )
    lumi2.SetTextAlign(   12 )
    lumi2.SetTextColor(    1 )
    lumi2.AddText("CMS Preliminary")


    parser = argparse.ArgumentParser()
    parser.add_argument('--scale', default="nominal", choices=['nominal', 'up', 'down', 'wup', 'wdown','qcdup','qcddown','JESup','JESdown'], help="Which TES?")
    options = parser.parse_args()

    fData=ROOT.TFile("qcdfiles_em/Data.root","r")
    fDY=ROOT.TFile("qcdfiles_em/DY.root","r")
    fTT=ROOT.TFile("qcdfiles_em/TT.root","r")
    fW=ROOT.TFile("qcdfiles_em/W.root","r")
    fVV=ROOT.TFile("qcdfiles_em/VV.root","r")

    h0_INOS=fData.Get("INOS0").Get("data_obs").Clone()
    h0_INOS.Add(fVV.Get("INOS0").Get("VV"),-1)
    h0_INOS.Add(fVV.Get("INOS0").Get("ST"),-1)
    h0_INOS.Add(fDY.Get("INOS0").Get("DY"),-1)
    h0_INOS.Add(fTT.Get("INOS0").Get("TT"),-1)
    h0_INOS_W=fW.Get("INOS0").Get("W").Clone()
    for i in range(1,h0_INOS_W.GetSize()):
 	h0_INOS_W.SetBinError(i,(h0_INOS_W.GetBinError(i)*h0_INOS_W.GetBinError(i)+0.20*0.20*h0_INOS_W.GetBinContent(i)*h0_INOS_W.GetBinContent(i))**0.5)
    h0_INOS.Add(h0_INOS_W,-1)
    #h0_INOS.Add(fW.Get("INOS0").Get("W"),-1)
    INOS0=h0_INOS.Clone()
    h0_INSS=fData.Get("INSS0").Get("data_obs").Clone()
    h0_INSS.Add(fVV.Get("INSS0").Get("VV"),-1)
    h0_INSS.Add(fVV.Get("INSS0").Get("ST"),-1)
    h0_INSS.Add(fDY.Get("INSS0").Get("DY"),-1)
    h0_INSS.Add(fTT.Get("INSS0").Get("TT"),-1)
    h0_INSS_W=fW.Get("INSS0").Get("W").Clone()
    for i in range(1,h0_INSS_W.GetSize()):
        h0_INSS_W.SetBinError(i,(h0_INSS_W.GetBinError(i)*h0_INSS_W.GetBinError(i)+0.20*0.20*h0_INSS_W.GetBinContent(i)*h0_INSS_W.GetBinContent(i))**0.5)
    h0_INSS.Add(h0_INSS_W,-1)
    #h0_INSS.Add(fW.Get("INSS0").Get("W"),-1)
    INSS0=h0_INSS.Clone()
    h0_INOS.Divide(h0_INSS)

    h0_closureOS=fData.Get("closureOS0").Get("data_obs").Clone()
    h0_closureOS.Add(fVV.Get("closureOS0").Get("VV"),-1)
    h0_closureOS.Add(fVV.Get("closureOS0").Get("ST"),-1)
    h0_closureOS.Add(fDY.Get("closureOS0").Get("DY"),-1)
    h0_closureOS.Add(fTT.Get("closureOS0").Get("TT"),-1)
    h0_closureOS.Add(fW.Get("closureOS0").Get("W"),-1)
    h0_closureSS=fData.Get("closureSS0").Get("data_obs").Clone()
    h0_closureSS.Add(fVV.Get("closureSS0").Get("VV"),-1)
    h0_closureSS.Add(fVV.Get("closureSS0").Get("ST"),-1)
    h0_closureSS.Add(fDY.Get("closureSS0").Get("DY"),-1)
    h0_closureSS.Add(fTT.Get("closureSS0").Get("TT"),-1)
    h0_closureSS.Add(fW.Get("closureSS0").Get("W"),-1)
    h0_closureOS.Divide(h0_closureSS)

    h1_INOS=fData.Get("INOS1").Get("data_obs").Clone()
    h1_INOS.Sumw2()
    h1_INOS.Add(fVV.Get("INOS1").Get("VV"),-1)
    h1_INOS.Add(fVV.Get("INOS1").Get("ST"),-1)
    h1_INOS.Add(fDY.Get("INOS1").Get("DY"),-1)
    h1_INOS.Add(fTT.Get("INOS1").Get("TT"),-1)
    h1_INOS.Add(fW.Get("INOS1").Get("W"),-1)
    INOS1=h1_INOS.Clone()
    h1_INSS=fData.Get("INSS1").Get("data_obs").Clone()
    h1_INSS.Sumw2()
    h1_INSS.Add(fVV.Get("INSS1").Get("VV"),-1)
    h1_INSS.Add(fVV.Get("INSS1").Get("ST"),-1)
    h1_INSS.Add(fDY.Get("INSS1").Get("DY"),-1)
    h1_INSS.Add(fTT.Get("INSS1").Get("TT"),-1)
    h1_INSS.Add(fW.Get("INSS1").Get("W"),-1)
    INSS1=h1_INSS.Clone()
    h1_INOS.Divide(h1_INSS)

    h1_closureOS=fData.Get("closureOS1").Get("data_obs").Clone()
    h1_closureOS.Add(fVV.Get("closureOS1").Get("VV"),-1)
    h1_closureOS.Add(fVV.Get("closureOS1").Get("ST"),-1)
    h1_closureOS.Add(fDY.Get("closureOS1").Get("DY"),-1)
    h1_closureOS.Add(fTT.Get("closureOS1").Get("TT"),-1)
    h1_closureOS.Add(fW.Get("closureOS1").Get("W"),-1)
    h1_closureSS=fData.Get("closureSS1").Get("data_obs").Clone()
    h1_closureSS.Add(fVV.Get("closureSS1").Get("VV"),-1)
    h1_closureSS.Add(fVV.Get("closureSS1").Get("ST"),-1)
    h1_closureSS.Add(fDY.Get("closureSS1").Get("DY"),-1)
    h1_closureSS.Add(fTT.Get("closureSS1").Get("TT"),-1)
    h1_closureSS.Add(fW.Get("closureSS1").Get("W"),-1)
    h1_closureOS.Divide(h1_closureSS)

    h2_INOS=fData.Get("INOS2").Get("data_obs").Clone()
    h2_INOS.Add(fVV.Get("INOS2").Get("VV"),-1)
    h2_INOS.Add(fVV.Get("INOS2").Get("ST"),-1)
    h2_INOS.Add(fDY.Get("INOS2").Get("DY"),-1)
    h2_INOS.Add(fTT.Get("INOS2").Get("TT"),-1)
    h2_INOS.Add(fW.Get("INOS2").Get("W"),-1)
    INOS2=h2_INOS.Clone()
    h2_INSS=fData.Get("INSS2").Get("data_obs").Clone()
    h2_INSS.Add(fVV.Get("INSS2").Get("VV"),-1)
    h2_INSS.Add(fVV.Get("INSS2").Get("ST"),-1)
    h2_INSS.Add(fDY.Get("INSS2").Get("DY"),-1)
    h2_INSS.Add(fTT.Get("INSS2").Get("TT"),-1)
    h2_INSS.Add(fW.Get("INSS2").Get("W"),-1)
    INSS2=h2_INSS.Clone()
    h2_INOS.Divide(h2_INSS)

    h2_closureOS=fData.Get("closureOS2").Get("data_obs").Clone()
    h2_closureOS.Add(fVV.Get("closureOS2").Get("VV"),-1)
    h2_closureOS.Add(fVV.Get("closureOS2").Get("ST"),-1)
    h2_closureOS.Add(fDY.Get("closureOS2").Get("DY"),-1)
    h2_closureOS.Add(fTT.Get("closureOS2").Get("TT"),-1)
    h2_closureOS.Add(fW.Get("closureOS2").Get("W"),-1)
    h2_closureSS=fData.Get("closureSS2").Get("data_obs").Clone()
    h2_closureSS.Add(fVV.Get("closureSS2").Get("VV"),-1)
    h2_closureSS.Add(fVV.Get("closureSS2").Get("ST"),-1)
    h2_closureSS.Add(fDY.Get("closureSS2").Get("DY"),-1)
    h2_closureSS.Add(fTT.Get("closureSS2").Get("TT"),-1)
    h2_closureSS.Add(fW.Get("closureSS2").Get("W"),-1)
    h2_closureOS.Divide(h2_closureSS)

    h_INOS=fData.Get("INOS").Get("data_obs").Clone()
    h_INOS.Add(fVV.Get("INOS").Get("VV"),-1)
    h_INOS.Add(fVV.Get("INOS").Get("ST"),-1)
    h_INOS.Add(fDY.Get("INOS").Get("DY"),-1)
    h_INOS.Add(fTT.Get("INOS").Get("TT"),-1)
    h_INOS.Add(fW.Get("INOS").Get("W"),-1)
    h_INSS=fData.Get("INSS").Get("data_obs").Clone()
    h_INSS.Add(fVV.Get("INSS").Get("VV"),-1)
    h_INSS.Add(fVV.Get("INSS").Get("ST"),-1)
    h_INSS.Add(fDY.Get("INSS").Get("DY"),-1)
    h_INSS.Add(fTT.Get("INSS").Get("TT"),-1)
    h_INSS.Add(fW.Get("INSS").Get("W"),-1)
    h_INOS.Divide(h_INSS)

    h_NIOS=fData.Get("NIOS").Get("data_obs").Clone()
    h_NIOS.Add(fVV.Get("NIOS").Get("VV"),-1)
    h_NIOS.Add(fVV.Get("NIOS").Get("ST"),-1)
    h_NIOS.Add(fDY.Get("NIOS").Get("DY"),-1)
    h_NIOS.Add(fTT.Get("NIOS").Get("TT"),-1)
    h_NIOS.Add(fW.Get("NIOS").Get("W"),-1)
    h_NISS=fData.Get("NISS").Get("data_obs").Clone()
    h_NISS.Add(fVV.Get("NISS").Get("VV"),-1)
    h_NISS.Add(fVV.Get("NISS").Get("ST"),-1)
    h_NISS.Add(fDY.Get("NISS").Get("DY"),-1)
    h_NISS.Add(fTT.Get("NISS").Get("TT"),-1)
    h_NISS.Add(fW.Get("NISS").Get("W"),-1)
    h_NIOS.Divide(h_NISS)

    h_NNOS=fData.Get("NNOS").Get("data_obs").Clone()
    h_NNOS.Add(fVV.Get("NNOS").Get("VV"),-1)
    h_NNOS.Add(fVV.Get("NNOS").Get("ST"),-1)
    h_NNOS.Add(fDY.Get("NNOS").Get("DY"),-1)
    h_NNOS.Add(fTT.Get("NNOS").Get("TT"),-1)
    h_NNOS.Add(fW.Get("NNOS").Get("W"),-1)
    h_NNSS=fData.Get("NNSS").Get("data_obs").Clone()
    h_NNSS.Add(fVV.Get("NNSS").Get("VV"),-1)
    h_NNSS.Add(fVV.Get("NNSS").Get("ST"),-1)
    h_NNSS.Add(fDY.Get("NNSS").Get("DY"),-1)
    h_NNSS.Add(fTT.Get("NNSS").Get("TT"),-1)
    h_NNSS.Add(fW.Get("NNSS").Get("W"),-1)
    h_NNOS.Divide(h_NNSS)

    h_correction=h_NIOS.Clone()
    h_correction.Divide(h_NNOS)

    h_closureOS=fData.Get("closureOS").Get("data_obs").Clone()
    h_closureOS.Add(fVV.Get("closureOS").Get("VV"),-1)
    h_closureOS.Add(fVV.Get("closureOS").Get("ST"),-1)
    h_closureOS.Add(fDY.Get("closureOS").Get("DY"),-1)
    h_closureOS.Add(fTT.Get("closureOS").Get("TT"),-1)
    h_closureOS.Add(fW.Get("closureOS").Get("W"),-1)
    h_closureSS=fData.Get("closureSS").Get("data_obs").Clone()
    h_closureSS.Add(fVV.Get("closureSS").Get("VV"),-1)
    h_closureSS.Add(fVV.Get("closureSS").Get("ST"),-1)
    h_closureSS.Add(fDY.Get("closureSS").Get("DY"),-1)
    h_closureSS.Add(fTT.Get("closureSS").Get("TT"),-1)
    h_closureSS.Add(fW.Get("closureSS").Get("W"),-1)
    h_closureOS.Divide(h_closureSS)


    ROOT.gStyle.SetOptStat(0)
    ROOT.gStyle.SetOptFit(1111)

    c=ROOT.TCanvas("canvas","",0,0,600,600)
    c.cd()
    h0_INOS.SetMinimum(1)
    h0_INOS.SetMaximum(3)
    h0_INOS.SetTitle("")
    h0_INOS.GetXaxis().SetTitle("#DeltaR(e,#mu)")
    h0_INOS.GetYaxis().SetTitle("OS-to-SS scale factor")
    h0_INOS.Draw("e")
    h0_INOS.Fit("pol1")
    lumi.Draw("same")
    lumi2.Draw("same")
    c.SaveAs("OSSSSF_0jet.png")

    h1_INOS.SetTitle("")
    h1_INOS.SetMinimum(1)
    h1_INOS.SetMaximum(3)
    h1_INOS.GetXaxis().SetTitle("#DeltaR(e,#mu)")
    h1_INOS.GetYaxis().SetTitle("OS-to-SS scale factor")
    h1_INOS.Draw("e")
    h1_INOS.Fit("pol1")
    lumi.Draw("same")
    lumi2.Draw("same")
    c.SaveAs("OSSSSF_1jet.png")

    h2_INOS.SetTitle("")
    h2_INOS.SetMinimum(1)
    h2_INOS.SetMaximum(3)
    h2_INOS.GetXaxis().SetTitle("#DeltaR(e,#mu)")
    h2_INOS.GetYaxis().SetTitle("OS-to-SS scale factor")
    h2_INOS.Draw("e")
    h2_INOS.Fit("pol1")
    lumi.Draw("same")
    lumi2.Draw("same")
    c.SaveAs("OSSSSF_2jet.png")

    h0_closureOS.SetTitle("")
    h0_closureOS.GetXaxis().SetTitle("p_{T}(#mu) (GeV)")
    h0_closureOS.GetYaxis().SetTitle("p_{T}(e) (GeV)")
    h0_closureOS.Draw("colz")
    h0_closureOS.Draw("TEXTsame")
    lumi.Draw("same")
    c.SaveAs("closure_0jet.png")

    h1_closureOS.SetTitle("")
    h1_closureOS.GetXaxis().SetTitle("p_{T}(#mu) (GeV)")
    h1_closureOS.GetYaxis().SetTitle("p_{T}(e) (GeV)")
    h1_closureOS.Draw("colz")
    h1_closureOS.Draw("TEXTsame")
    lumi.Draw("same")
    c.SaveAs("closure_1jet.png")

    h2_closureOS.SetTitle("")
    h2_closureOS.GetXaxis().SetTitle("p_{T}(#mu) (GeV)")
    h2_closureOS.GetYaxis().SetTitle("p_{T}(e) (GeV)")
    h2_closureOS.Draw("colz")
    h2_closureOS.Draw("TEXTsame")
    lumi.Draw("same")
    c.SaveAs("closure_2jet.png")

    h_closureOS.SetTitle("")
    h_closureOS.SetMinimum(0.7)
    h_closureOS.SetMaximum(1.3)
    h_closureOS.GetXaxis().SetTitle("p_{T}(#mu) (GeV)")
    h_closureOS.GetYaxis().SetTitle("p_{T}(e) (GeV)")
    h_closureOS.Draw("colz")
    h_closureOS.Draw("TEXTsame")
    lumi.Draw("same")
    c.SaveAs("closure.png")

    h_correction.SetTitle("")
    h_correction.SetMinimum(0.7)
    h_correction.SetMaximum(1.00)
    h_correction.GetXaxis().SetTitle("p_{T}(#mu) (GeV)")
    h_correction.GetYaxis().SetTitle("p_{T}(e) (GeV)")
    h_correction.Draw("colz")
    h_correction.Draw("TEXTsame")
    lumi.Draw("same")
    c.SaveAs("correction.png")

    fout=ROOT.TFile("qcdfiles_em/closure.root","recreate")
    fout.cd()
    h_closureOS.SetName("closureOS")
    h0_closureOS.SetName("closureOS0")
    h1_closureOS.SetName("closureOS1")
    h2_closureOS.SetName("closureOS2")
    h_correction.SetName("correction")
    h_closureOS.Write()
    h0_closureOS.Write()
    h1_closureOS.Write()
    h2_closureOS.Write()
    h_correction.Write()
    fout.Close()

    fSub=ROOT.TFile("qcdfiles_em/Sub.root","recreate")
    fSub.cd()
    INOS0.SetName("INOS0")
    INOS0.Write()
    INSS0.SetName("INSS0")
    INSS0.Write()
    INOS1.SetName("INOS1")
    INOS1.Write()
    INSS1.SetName("INSS1")
    INSS1.Write()
    INOS2.SetName("INOS2")
    INOS2.Write()
    INSS2.SetName("INSS2")
    INSS2.Write()
    fSub.Close()



