if __name__ == "__main__":

    import ROOT
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('--scale', default="nominal", choices=['nominal', 'up', 'down', 'wup', 'wdown','qcdup','qcddown','JESup','JESdown'], help="Which TES?")
    options = parser.parse_args()

    nbhist=1

    fData=ROOT.TFile("mufakefiles/Data.root","r")
    fDY=ROOT.TFile("mufakefiles/DY.root","r")
    fTT=ROOT.TFile("mufakefiles/TTscaled.root","r")
    fVV=ROOT.TFile("mufakefiles/VV.root","r")
    fW=ROOT.TFile("mufakefiles/Wscaled.root","r")
    fout=ROOT.TFile("mufakefiles/Fake.root","recreate")

    postfix=[""]

    fout.cd()
    dir0=fout.mkdir("ZLmupass")
    dir0.cd()
    for k in range(0,nbhist):
      myh=fData.Get("ZLmupassSSAI").Get("data_obs").Clone()
      myh.Add(fDY.Get("ZLmupassSSAI").Get("DYL").Clone(),-1)
      myh.Add(fDY.Get("ZLmupassSSAI").Get("DYT").Clone(),-1)
      myh.Add(fDY.Get("ZLmupassSSAI").Get("DYJ").Clone(),-1)
      myh.Add(fTT.Get("ZLmupassSSAI").Get("TTT").Clone(),-1)
      myh.Add(fTT.Get("ZLmupassSSAI").Get("TTL").Clone(),-1)
      myh.Add(fTT.Get("ZLmupassSSAI").Get("TTJ").Clone(),-1)
      myh.Add(fVV.Get("ZLmupassSSAI").Get("VVT").Clone(),-1)
      myh.Add(fVV.Get("ZLmupassSSAI").Get("VVL").Clone(),-1)
      myh.Add(fVV.Get("ZLmupassSSAI").Get("VVJ").Clone(),-1)
      myh.Add(fVV.Get("ZLmupassSSAI").Get("STT").Clone(),-1)
      myh.Add(fVV.Get("ZLmupassSSAI").Get("STL").Clone(),-1)
      myh.Add(fVV.Get("ZLmupassSSAI").Get("STJ").Clone(),-1)
      myh.Add(fW.Get("ZLmupassSSAI").Get("W").Clone(),-1)
      myh2=fData.Get("ZLmupassSS").Get("data_obs").Clone()
      myh2.Add(fDY.Get("ZLmupassSS").Get("DYL").Clone(),-1)
      myh2.Add(fDY.Get("ZLmupassSS").Get("DYT").Clone(),-1)
      myh2.Add(fDY.Get("ZLmupassSS").Get("DYJ").Clone(),-1)
      myh2.Add(fTT.Get("ZLmupassSS").Get("TTT").Clone(),-1)
      myh2.Add(fTT.Get("ZLmupassSS").Get("TTL").Clone(),-1)
      myh2.Add(fTT.Get("ZLmupassSS").Get("TTJ").Clone(),-1)
      myh2.Add(fVV.Get("ZLmupassSS").Get("VVT").Clone(),-1)
      myh2.Add(fVV.Get("ZLmupassSS").Get("VVL").Clone(),-1)
      myh2.Add(fVV.Get("ZLmupassSS").Get("VVJ").Clone(),-1)
      myh2.Add(fVV.Get("ZLmupassSS").Get("STT").Clone(),-1)
      myh2.Add(fVV.Get("ZLmupassSS").Get("STL").Clone(),-1)
      myh2.Add(fVV.Get("ZLmupassSS").Get("STJ").Clone(),-1)
      myh2.Add(fW.Get("ZLmupassSS").Get("W").Clone(),-1)
      myh.Scale(myh2.Integral()/myh.Integral())
      myh.Scale(1.06)
      myh.SetName("QCD"+postfix[k])
      myh.Write()

    dir1=fout.mkdir("ZLmufail")
    dir1.cd()
    for k in range(0,nbhist):
      myh=fData.Get("ZLmufailSSAI").Get("data_obs").Clone()
      myh.Add(fDY.Get("ZLmufailSSAI").Get("DYL").Clone(),-1)
      myh.Add(fDY.Get("ZLmufailSSAI").Get("DYT").Clone(),-1)
      myh.Add(fDY.Get("ZLmufailSSAI").Get("DYJ").Clone(),-1)
      myh.Add(fTT.Get("ZLmufailSSAI").Get("TTT").Clone(),-1)
      myh.Add(fTT.Get("ZLmufailSSAI").Get("TTL").Clone(),-1)
      myh.Add(fTT.Get("ZLmufailSSAI").Get("TTJ").Clone(),-1)
      myh.Add(fVV.Get("ZLmufailSSAI").Get("VVT").Clone(),-1)
      myh.Add(fVV.Get("ZLmufailSSAI").Get("VVL").Clone(),-1)
      myh.Add(fVV.Get("ZLmufailSSAI").Get("VVJ").Clone(),-1)
      myh.Add(fVV.Get("ZLmufailSSAI").Get("STT").Clone(),-1)
      myh.Add(fVV.Get("ZLmufailSSAI").Get("STL").Clone(),-1)
      myh.Add(fVV.Get("ZLmufailSSAI").Get("STL").Clone(),-1)
      myh.Add(fW.Get("ZLmufailSSAI").Get("W").Clone(),-1)
      myh2=fData.Get("ZLmufailSS").Get("data_obs").Clone()
      myh2.Add(fDY.Get("ZLmufailSS").Get("DYL").Clone(),-1)
      myh2.Add(fDY.Get("ZLmufailSS").Get("DYT").Clone(),-1)
      myh2.Add(fDY.Get("ZLmufailSS").Get("DYJ").Clone(),-1)
      myh2.Add(fTT.Get("ZLmufailSS").Get("TTT").Clone(),-1)
      myh2.Add(fTT.Get("ZLmufailSS").Get("TTL").Clone(),-1)
      myh2.Add(fTT.Get("ZLmufailSS").Get("TTJ").Clone(),-1)
      myh2.Add(fVV.Get("ZLmufailSS").Get("VVT").Clone(),-1)
      myh2.Add(fVV.Get("ZLmufailSS").Get("VVL").Clone(),-1)
      myh2.Add(fVV.Get("ZLmufailSS").Get("VVJ").Clone(),-1)
      myh2.Add(fVV.Get("ZLmufailSS").Get("STT").Clone(),-1)
      myh2.Add(fVV.Get("ZLmufailSS").Get("STL").Clone(),-1)
      myh2.Add(fVV.Get("ZLmufailSS").Get("STJ").Clone(),-1)
      myh2.Add(fW.Get("ZLmufailSS").Get("W").Clone(),-1)
      myh.Scale(myh2.Integral()/myh.Integral())
      myh.Scale(1.06)
      myh.SetName("QCD"+postfix[k])
      myh.Write()

    dir2=fout.mkdir("ZLmupassMTOS")
    dir2.cd()
    for k in range(0,nbhist):
      myh=fData.Get("ZLmupassMTSS").Get("data_obs").Clone()
      myh.Add(fDY.Get("ZLmupassMTSS").Get("DYL").Clone(),-1)
      myh.Add(fDY.Get("ZLmupassMTSS").Get("DYT").Clone(),-1)
      myh.Add(fDY.Get("ZLmupassMTSS").Get("DYJ").Clone(),-1)
      myh.Add(fTT.Get("ZLmupassMTSS").Get("TTT").Clone(),-1)
      myh.Add(fTT.Get("ZLmupassMTSS").Get("TTL").Clone(),-1)
      myh.Add(fTT.Get("ZLmupassMTSS").Get("TTL").Clone(),-1)
      myh.Add(fVV.Get("ZLmupassMTSS").Get("VVT").Clone(),-1)
      myh.Add(fVV.Get("ZLmupassMTSS").Get("VVL").Clone(),-1)
      myh.Add(fVV.Get("ZLmupassMTSS").Get("VVJ").Clone(),-1)
      myh.Add(fVV.Get("ZLmupassMTSS").Get("STT").Clone(),-1)
      myh.Add(fVV.Get("ZLmupassMTSS").Get("STL").Clone(),-1)
      myh.Add(fVV.Get("ZLmupassMTSS").Get("STJ").Clone(),-1)
      myh.Add(fW.Get("ZLmupassMTSS").Get("W").Clone(),-1)
      myh.SetName("QCD"+postfix[k])
      myh.Scale(1.06)
      myh.Write()

    dir3=fout.mkdir("ZLmufailMTOS")
    dir3.cd()
    for k in range(0,nbhist):
      myh=fData.Get("ZLmufailMTSS").Get("data_obs").Clone()
      myh.Add(fDY.Get("ZLmufailMTSS").Get("DYL").Clone(),-1)
      myh.Add(fDY.Get("ZLmufailMTSS").Get("DYT").Clone(),-1)
      myh.Add(fDY.Get("ZLmufailMTSS").Get("DYJ").Clone(),-1)
      myh.Add(fTT.Get("ZLmufailMTSS").Get("TTT").Clone(),-1)
      myh.Add(fTT.Get("ZLmufailMTSS").Get("TTL").Clone(),-1)
      myh.Add(fTT.Get("ZLmufailMTSS").Get("TTJ").Clone(),-1)
      myh.Add(fVV.Get("ZLmufailMTSS").Get("VVT").Clone(),-1)
      myh.Add(fVV.Get("ZLmufailMTSS").Get("VVL").Clone(),-1)
      myh.Add(fVV.Get("ZLmufailMTSS").Get("VVL").Clone(),-1)
      myh.Add(fVV.Get("ZLmufailMTSS").Get("STT").Clone(),-1)
      myh.Add(fVV.Get("ZLmufailMTSS").Get("STL").Clone(),-1)
      myh.Add(fVV.Get("ZLmufailMTSS").Get("STJ").Clone(),-1)
      myh.Add(fW.Get("ZLmufailMTSS").Get("W").Clone(),-1)
      myh.SetName("QCD"+postfix[k])
      myh.Scale(1.06)
      myh.Write()


