if __name__ == "__main__":

    import ROOT
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('--scale', default="nominal", choices=['nominal', 'up', 'down', 'wup', 'wdown','qcdup','qcddown','JESup','JESdown'], help="Which TES?")
    options = parser.parse_args()

    fDY=ROOT.TFile("files_nominal_mt/DY.root","r")
    fEmbedded=ROOT.TFile("files_nominal_mt/Embedded.root","r")
    fEWKZ=ROOT.TFile("files_nominal_mt/EWKZ.root","r")
    fDYlow=ROOT.TFile("files_nominal_mt/DYlow.root","r")
    fW=ROOT.TFile("files_nominal_mt/W.root","r")
    fTT=ROOT.TFile("files_nominal_mt/TT.root","r")
    fVV=ROOT.TFile("files_nominal_mt/VV.root","r")
    fData=ROOT.TFile("files_nominal_mt/Data.root","r")
    fout=ROOT.TFile("files_nominal_mt/fractions.root","recreate")

    h_0jet_w=fW.Get("AI0jet/W")
    h_0jet_w.Add(fDY.Get("AI0jet/ZJ"))
    h_0jet_w.Add(fVV.Get("AI0jet/VVJ"))
    h_0jet_tt=fTT.Get("AI0jet/TTJ")
    h_0jet_data=fData.Get("AI0jet/data_obs")
    h_0jet_real=fEmbedded.Get("AI0jet/embedded")
    h_0jet_real.Add(fDY.Get("AI0jet/ZL"))
    h_0jet_real.Add(fDYlow.Get("AI0jet/DYlow"))
    h_0jet_real.Add(fEWKZ.Get("AI0jet/EWKZ"))
    h_0jet_real.Add(fTT.Get("AI0jet/TTT"))
    h_0jet_real.Add(fTT.Get("AI0jet/TTL"))
    h_0jet_real.Add(fVV.Get("AI0jet/VVT"))
    h_0jet_real.Add(fVV.Get("AI0jet/VVL"))
    h_0jet_qcd=h_0jet_data.Clone()
    h_0jet_qcd.Add(h_0jet_real,-1)
    h_0jet_qcd.Add(h_0jet_tt,-1)
    h_0jet_qcd.Add(h_0jet_w,-1)
    h_0jet_w.SetName("frac_w_0jet")
    h_0jet_qcd.SetName("frac_qcd_0jet")
    h_0jet_tt.SetName("frac_tt_0jet")
    h_0jet_data.SetName("frac_data_0jet")

    h_boosted_w=fW.Get("AIboosted/W")
    h_boosted_w.Add(fDY.Get("AIboosted/ZJ"))
    h_boosted_w.Add(fVV.Get("AIboosted/VVJ"))
    h_boosted_tt=fTT.Get("AIboosted/TTJ")
    h_boosted_data=fData.Get("AIboosted/data_obs")
    h_boosted_real=fEmbedded.Get("AIboosted/embedded")
    h_boosted_real.Add(fDY.Get("AIboosted/ZL"))
    h_boosted_real.Add(fDYlow.Get("AIboosted/DYlow"))
    h_boosted_real.Add(fEWKZ.Get("AIboosted/EWKZ"))
    h_boosted_real.Add(fTT.Get("AIboosted/TTT"))
    h_boosted_real.Add(fTT.Get("AIboosted/TTL"))
    h_boosted_real.Add(fVV.Get("AIboosted/VVT"))
    h_boosted_real.Add(fVV.Get("AIboosted/VVL"))
    h_boosted_qcd=h_boosted_data.Clone()
    h_boosted_qcd.Add(h_boosted_real,-1)
    h_boosted_qcd.Add(h_boosted_tt,-1)
    h_boosted_qcd.Add(h_boosted_w,-1)
    h_boosted_w.SetName("frac_w_boosted")
    h_boosted_qcd.SetName("frac_qcd_boosted")
    h_boosted_tt.SetName("frac_tt_boosted")
    h_boosted_data.SetName("frac_data_boosted")

    h_vbf_w=fW.Get("AIvbf/W")
    h_vbf_w.Add(fDY.Get("AIvbf/ZJ"))
    h_vbf_w.Add(fVV.Get("AIvbf/VVJ"))
    h_vbf_tt=fTT.Get("AIvbf/TTJ")
    h_vbf_data=fData.Get("AIvbf/data_obs")
    h_vbf_real=fEmbedded.Get("AIvbf/embedded")
    h_vbf_real.Add(fDY.Get("AIvbf/ZL"))
    h_vbf_real.Add(fDYlow.Get("AIvbf/DYlow"))
    h_vbf_real.Add(fEWKZ.Get("AIvbf/EWKZ"))
    h_vbf_real.Add(fTT.Get("AIvbf/TTT"))
    h_vbf_real.Add(fTT.Get("AIvbf/TTL"))
    h_vbf_real.Add(fVV.Get("AIvbf/VVT"))
    h_vbf_real.Add(fVV.Get("AIvbf/VVL"))
    h_vbf_qcd=h_vbf_data.Clone()
    h_vbf_qcd.Add(h_vbf_real,-1)
    h_vbf_qcd.Add(h_vbf_tt,-1)
    h_vbf_qcd.Add(h_vbf_w,-1)
    h_vbf_w.SetName("frac_w_vbf")
    h_vbf_qcd.SetName("frac_qcd_vbf")
    h_vbf_tt.SetName("frac_tt_vbf")
    h_vbf_data.SetName("frac_data_vbf")

    fout.cd()
    h_0jet_w.Write()
    h_0jet_tt.Write()
    h_0jet_qcd.Write()
    h_0jet_data.Write()
    h_boosted_w.Write()
    h_boosted_tt.Write()
    h_boosted_qcd.Write()
    h_boosted_data.Write()
    h_vbf_w.Write()
    h_vbf_tt.Write()
    h_vbf_qcd.Write()
    h_vbf_data.Write()
