if __name__ == "__main__":

    import ROOT
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('--scale', default="nominal", choices=['nominal', 'up', 'down', 'wup', 'wdown','qcdup','qcddown','JESup','JESdown'], help="Which TES?")
    options = parser.parse_args()

    nbhist=1

    fData=ROOT.TFile("efakefiles/Data.root","r")
    fDY=ROOT.TFile("efakefiles/DY.root","r")
    fTT=ROOT.TFile("efakefiles/TTscaled.root","r")
    fVV=ROOT.TFile("efakefiles/VV.root","r")
    fW=ROOT.TFile("efakefiles/Wscaled.root","r")
    fout=ROOT.TFile("efakefiles/Fake.root","recreate")

    postfix=[""]

    fout.cd()
    dir0=fout.mkdir("ZLepass")
    dir0.cd()
    for k in range(0,nbhist):
      myh=fData.Get("ZLepassSSAI").Get("data_obs").Clone()
      myh.Add(fDY.Get("ZLepassSSAI").Get("DYL").Clone(),-1)
      myh.Add(fDY.Get("ZLepassSSAI").Get("DYT").Clone(),-1)
      myh.Add(fDY.Get("ZLepassSSAI").Get("DYJ").Clone(),-1)
      myh.Add(fTT.Get("ZLepassSSAI").Get("TTT").Clone(),-1)
      myh.Add(fTT.Get("ZLepassSSAI").Get("TTL").Clone(),-1)
      myh.Add(fTT.Get("ZLepassSSAI").Get("TTJ").Clone(),-1)
      myh.Add(fVV.Get("ZLepassSSAI").Get("VVT").Clone(),-1)
      myh.Add(fVV.Get("ZLepassSSAI").Get("VVL").Clone(),-1)
      myh.Add(fVV.Get("ZLepassSSAI").Get("VVJ").Clone(),-1)
      myh.Add(fVV.Get("ZLepassSSAI").Get("STT").Clone(),-1)
      myh.Add(fVV.Get("ZLepassSSAI").Get("STL").Clone(),-1)
      myh.Add(fVV.Get("ZLepassSSAI").Get("STJ").Clone(),-1)
      myh.Add(fW.Get("ZLepassSSAI").Get("W").Clone(),-1)
      myh2=fData.Get("ZLepassSS").Get("data_obs").Clone()
      myh2.Add(fDY.Get("ZLepassSS").Get("DYL").Clone(),-1)
      myh2.Add(fDY.Get("ZLepassSS").Get("DYT").Clone(),-1)
      myh2.Add(fDY.Get("ZLepassSS").Get("DYJ").Clone(),-1)
      myh2.Add(fTT.Get("ZLepassSS").Get("TTT").Clone(),-1)
      myh2.Add(fTT.Get("ZLepassSS").Get("TTL").Clone(),-1)
      myh2.Add(fTT.Get("ZLepassSS").Get("TTJ").Clone(),-1)
      myh2.Add(fVV.Get("ZLepassSS").Get("VVT").Clone(),-1)
      myh2.Add(fVV.Get("ZLepassSS").Get("VVL").Clone(),-1)
      myh2.Add(fVV.Get("ZLepassSS").Get("VVJ").Clone(),-1)
      myh2.Add(fVV.Get("ZLepassSS").Get("STT").Clone(),-1)
      myh2.Add(fVV.Get("ZLepassSS").Get("STL").Clone(),-1)
      myh2.Add(fVV.Get("ZLepassSS").Get("STJ").Clone(),-1)
      myh2.Add(fW.Get("ZLepassSS").Get("W").Clone(),-1)
      myh.Scale(myh2.Integral()/myh.Integral())
      myh.Scale(1.06)
      myh.SetName("QCD"+postfix[k])
      myh.Write()

    dir1=fout.mkdir("ZLefail")
    dir1.cd()
    for k in range(0,nbhist):
      myh=fData.Get("ZLefailSSAI").Get("data_obs").Clone()
      myh.Add(fDY.Get("ZLefailSSAI").Get("DYL").Clone(),-1)
      myh.Add(fDY.Get("ZLefailSSAI").Get("DYT").Clone(),-1)
      myh.Add(fDY.Get("ZLefailSSAI").Get("DYJ").Clone(),-1)
      myh.Add(fTT.Get("ZLefailSSAI").Get("TTT").Clone(),-1)
      myh.Add(fTT.Get("ZLefailSSAI").Get("TTL").Clone(),-1)
      myh.Add(fTT.Get("ZLefailSSAI").Get("TTJ").Clone(),-1)
      myh.Add(fVV.Get("ZLefailSSAI").Get("VVT").Clone(),-1)
      myh.Add(fVV.Get("ZLefailSSAI").Get("VVL").Clone(),-1)
      myh.Add(fVV.Get("ZLefailSSAI").Get("VVJ").Clone(),-1)
      myh.Add(fVV.Get("ZLefailSSAI").Get("STT").Clone(),-1)
      myh.Add(fVV.Get("ZLefailSSAI").Get("STL").Clone(),-1)
      myh.Add(fVV.Get("ZLefailSSAI").Get("STL").Clone(),-1)
      myh.Add(fW.Get("ZLefailSSAI").Get("W").Clone(),-1)
      myh2=fData.Get("ZLefailSS").Get("data_obs").Clone()
      myh2.Add(fDY.Get("ZLefailSS").Get("DYL").Clone(),-1)
      myh2.Add(fDY.Get("ZLefailSS").Get("DYT").Clone(),-1)
      myh2.Add(fDY.Get("ZLefailSS").Get("DYJ").Clone(),-1)
      myh2.Add(fTT.Get("ZLefailSS").Get("TTT").Clone(),-1)
      myh2.Add(fTT.Get("ZLefailSS").Get("TTL").Clone(),-1)
      myh2.Add(fTT.Get("ZLefailSS").Get("TTJ").Clone(),-1)
      myh2.Add(fVV.Get("ZLefailSS").Get("VVT").Clone(),-1)
      myh2.Add(fVV.Get("ZLefailSS").Get("VVL").Clone(),-1)
      myh2.Add(fVV.Get("ZLefailSS").Get("VVJ").Clone(),-1)
      myh2.Add(fVV.Get("ZLefailSS").Get("STT").Clone(),-1)
      myh2.Add(fVV.Get("ZLefailSS").Get("STL").Clone(),-1)
      myh2.Add(fVV.Get("ZLefailSS").Get("STJ").Clone(),-1)
      myh2.Add(fW.Get("ZLefailSS").Get("W").Clone(),-1)
      myh.Scale(myh2.Integral()/myh.Integral())
      myh.Scale(1.06)
      myh.SetName("QCD"+postfix[k])
      myh.Write()

    dir2=fout.mkdir("ZLepassMTOS")
    dir2.cd()
    for k in range(0,nbhist):
      myh=fData.Get("ZLepassMTSS").Get("data_obs").Clone()
      myh.Add(fDY.Get("ZLepassMTSS").Get("DYL").Clone(),-1)
      myh.Add(fDY.Get("ZLepassMTSS").Get("DYT").Clone(),-1)
      myh.Add(fDY.Get("ZLepassMTSS").Get("DYJ").Clone(),-1)
      myh.Add(fTT.Get("ZLepassMTSS").Get("TTT").Clone(),-1)
      myh.Add(fTT.Get("ZLepassMTSS").Get("TTL").Clone(),-1)
      myh.Add(fTT.Get("ZLepassMTSS").Get("TTL").Clone(),-1)
      myh.Add(fVV.Get("ZLepassMTSS").Get("VVT").Clone(),-1)
      myh.Add(fVV.Get("ZLepassMTSS").Get("VVL").Clone(),-1)
      myh.Add(fVV.Get("ZLepassMTSS").Get("VVJ").Clone(),-1)
      myh.Add(fVV.Get("ZLepassMTSS").Get("STT").Clone(),-1)
      myh.Add(fVV.Get("ZLepassMTSS").Get("STL").Clone(),-1)
      myh.Add(fVV.Get("ZLepassMTSS").Get("STJ").Clone(),-1)
      myh.Add(fW.Get("ZLepassMTSS").Get("W").Clone(),-1)
      myh.SetName("QCD"+postfix[k])
      myh.Scale(1.06)
      myh.Write()

    dir3=fout.mkdir("ZLefailMTOS")
    dir3.cd()
    for k in range(0,nbhist):
      myh=fData.Get("ZLefailMTSS").Get("data_obs").Clone()
      myh.Add(fDY.Get("ZLefailMTSS").Get("DYL").Clone(),-1)
      myh.Add(fDY.Get("ZLefailMTSS").Get("DYT").Clone(),-1)
      myh.Add(fDY.Get("ZLefailMTSS").Get("DYJ").Clone(),-1)
      myh.Add(fTT.Get("ZLefailMTSS").Get("TTT").Clone(),-1)
      myh.Add(fTT.Get("ZLefailMTSS").Get("TTL").Clone(),-1)
      myh.Add(fTT.Get("ZLefailMTSS").Get("TTJ").Clone(),-1)
      myh.Add(fVV.Get("ZLefailMTSS").Get("VVT").Clone(),-1)
      myh.Add(fVV.Get("ZLefailMTSS").Get("VVL").Clone(),-1)
      myh.Add(fVV.Get("ZLefailMTSS").Get("VVL").Clone(),-1)
      myh.Add(fVV.Get("ZLefailMTSS").Get("STT").Clone(),-1)
      myh.Add(fVV.Get("ZLefailMTSS").Get("STL").Clone(),-1)
      myh.Add(fVV.Get("ZLefailMTSS").Get("STJ").Clone(),-1)
      myh.Add(fW.Get("ZLefailMTSS").Get("W").Clone(),-1)
      myh.SetName("QCD"+postfix[k])
      myh.Scale(1.06)
      myh.Write()


