  float genweight,genM,genpT,pt_top1,pt_top2;
  float photonIso_2, puIso_2, chargedIso_2, neutralIso_2,metcor,metcorphi;
  float byCombinedIsolationDeltaBetaCorrRaw3Hits_2, byIsolationMVA3oldDMwLTraw_2;
  float pt_1,pt_2,px_1,px_2,py_1,py_2,pz_1,pz_2,eta_1,eta_2,phi_1,phi_2,iso_1,e_1,e_2,m_1,m_2; 
  float flag_BadChargedCandidate, flag_BadPFMuon, flag_EcalDeadCellTriggerPrimitive, flag_HBHENoise, flag_HBHENoiseIso, flag_badCloneMuon, flag_badGlobalMuon, flag_eeBadSc, flag_globalTightHalo2016, flag_goodVertices, flag_globalSuperTightHalo2016, flag_badMuons, flag_duplicateMuons, flag_ecalBadCalib;
  int gen_match_1, gen_match_2;
  int nbtag;
  float numGenJets;
  int run, lumi, evt;
  float met_UESUp, met_UESDown, metphi_UESUp, metphi_UESDown;
  float Rivet_stage1_cat_pTjet30GeV,Rivet_stage0_cat, Rivet_higgsPt, Rivet_nJets30;
  int nup,njets;
  int njets_JetEta0to3Up, njets_JetEta0to5Up, njets_JetRelativeSampleUp, njets_JetRelativeBalUp, njets_JetEta3to5Up, njets_JetEta0to3Down, njets_JetEta0to5Down, njets_JetRelativeSampleDown, njets_JetRelativeBalDown, njets_JetEta3to5Down;
  float mjj_JetEta0to3Up, mjj_JetEta0to5Up, mjj_JetRelativeSampleUp, mjj_JetRelativeBalUp, mjj_JetEta3to5Up, mjj_JetEta0to3Down, mjj_JetEta0to5Down, mjj_JetRelativeSampleDown, mjj_JetRelativeBalDown, mjj_JetEta3to5Down;
  float m_sv, m_sv_01UP, m_sv_01DOWN, m_sv_10UP, m_sv_10DOWN, m_sv_11UP, m_sv_11DOWN, m_sv_UESUp, m_sv_UESDown;
  float m_sv_ResponseUp, m_sv_ResolutionUp, m_sv_JetEta0to3Up, m_sv_JetEta3to5Up, m_sv_JetEta0to5Up, m_sv_JetRelativeSampleUp, m_sv_JetRelativeBalUp;
  float m_sv_ResponseDown, m_sv_ResolutionDown, m_sv_JetEta0to3Down, m_sv_JetEta3to5Down, m_sv_JetEta0to5Down, m_sv_JetRelativeSampleDown, m_sv_JetRelativeBalDown;
  float met_responseUp, met_responseDown, met_resolutionUp, met_resolutionDown;
  float metphi_responseUp, metphi_responseDown, metphi_resolutionUp, metphi_resolutionDown;
  float met_JetEta0to3Up, met_JetEta0to3Down, metphi_JetEta0to3Up, metphi_JetEta0to3Down;
  float met_JetEta0to5Up, met_JetEta0to5Down, metphi_JetEta0to5Up, metphi_JetEta0to5Down;
  float met_JetEta3to5Up, met_JetEta3to5Down, metphi_JetEta3to5Up, metphi_JetEta3to5Down;
  float met_JetRelativeSampleUp, met_JetRelativeSampleDown, metphi_JetRelativeSampleUp, metphi_JetRelativeSampleDown;
  float met_JetRelativeBalUp, met_JetRelativeBalDown, metphi_JetRelativeBalUp, metphi_JetRelativeBalDown;
  float npv, jpt_1,mjj, jeta_1, jeta_2, jpt_2, jphi_1, jphi_2;
  float q_1,q_2;
  float met, metphi, met_px, met_py;
  float bpt_1, beta_1, bphi_1, bflavor_1, bpt_2, beta_2, bphi_2, bflavor_2;
  float againstElectronVLooseMVA6_2,againstElectronLooseMVA6_2,againstElectronMediumMVA6_2,againstElectronTightMVA6_2,againstElectronVTightMVA6_2;
  float againstMuonLoose3_2,againstMuonTight3_2;
  float byVVLooseIsolationMVArun2v2DBoldDMwLT_2, byVLooseIsolationMVArun2v2DBoldDMwLT_2, byLooseIsolationMVArun2v2DBoldDMwLT_2, byMediumIsolationMVArun2v2DBoldDMwLT_2, byTightIsolationMVArun2v2DBoldDMwLT_2, byVTightIsolationMVArun2v2DBoldDMwLT_2, byVVTightIsolationMVArun2v2DBoldDMwLT_2;
  float againstElectronVLooseMVA6_1,againstElectronLooseMVA6_1,againstElectronMediumMVA6_1,againstElectronTightMVA6_1,againstElectronVTightMVA6_1;
  float againstMuonLoose3_1,againstMuonTight3_1;
  float byVVLooseIsolationMVArun2v2DBoldDMwLT_1, byVLooseIsolationMVArun2v2DBoldDMwLT_1, byLooseIsolationMVArun2v2DBoldDMwLT_1, byMediumIsolationMVArun2v2DBoldDMwLT_1, byTightIsolationMVArun2v2DBoldDMwLT_1, byVTightIsolationMVArun2v2DBoldDMwLT_1, byVVTightIsolationMVArun2v2DBoldDMwLT_1;
  float l2_decayMode, l1_decayMode;
  float decayModeFinding_2;
  float puweight;
  float npu;
  int NUP;
  float passDoubleTightTau35TightID, passDoubleMediumTau40TightID, passDoubleTightTau40;
  float matchDoubleTightTau35TightID_1, matchDoubleMediumTau40TightID_1, matchDoubleTightTau40_1;
  float filterDoubleTightTau35TightID_1, filterDoubleMediumTau40TightID_1, filterDoubleTightTau40_1;
  float matchDoubleTightTau35TightID_2, matchDoubleMediumTau40TightID_2, matchDoubleTightTau40_2;
  float filterDoubleTightTau35TightID_2, filterDoubleMediumTau40TightID_2, filterDoubleTightTau40_2;
